### ISSUE TITLE
Tag a quest with CCSS ELA (English Language Arts) standards

### ISSUE THREAD

**Issue by EveTulbert** [freedomgames/Planet-Lab#43]
Users should be able to tag a quest (learning materials) with a ELA standard from a drop down list. 

See CCSS ELA standards. 
https://docs.google.com/spreadsheets/d/1jDq7fswDis3r2oEljzksMsWm4Dr9eG9u2DFl-9TOt9c/edit#gid=0

**Comment by andymcguinness** [comment]
This applies to the old MVP.
