### ISSUE TITLE
Search Functionality

### ISSUE THREAD

**Issue by EveTulbert** [freedomgames/Planet-Lab#50]
Users can search by the following qualifiers:  (See user stories list:  https://docs.google.com/spreadsheets/d/1UUaUgUu53LTpYuc69l8z2313leMX3Is0f5X4-l6FCsg/edit#gid=1272627328) 

1) KEYWORDS

2) STANDARDS: 
NGSS Standard
CCSS Standard
ELP Standard

**Comment by andymcguinness** [comment]
This applies to the old MVP.
