### ISSUE TITLE
GENERAL NOTES ON SEARCH / TAGS

### ISSUE THREAD

**Issue by EveTulbert** [freedomgames/Planet-Lab#51]
Hi!  

The overall design for the Selective Drop Down menu is depicted HERE
![pres--structuredsearch copy](https://cloud.githubusercontent.com/assets/12886327/8881619/ef614e00-3206-11e5-9bf2-dfb429ca9afe.png)

The basic idea is to create tiers of searching based on grade level standards and other qualifiers. 

QUESTION: 
If we want to call standards, do we call them from a JSON file on the Heroku side? 

Config.py:  Information about calling from Database

S3 Server:  where all the large static files are stored, IMAGES, SOUNDS VIDEO
Heroku Hosting: Codebase, database, user information, (anything searchable)

Potentially helpful links: 
https://www.codementor.io/angularjs/tutorial/create-dropdown-control
http://www.w3schools.com/sql/sql_where.asp  SEE SQL Select, SEE SQL Where

**Comment by andymcguinness** [comment]
This applies to the old MVP.
